/** Connection and conversation contracts (docs/API.md §6.6-§6.7). */
import { z } from 'zod';

import { CONNECTION_ACTIONS, CONNECTION_STATUSES } from '../domain/workflows.js';

import { Cursor, IsoDateTime, Uuid, cursorPage } from './common.js';
import { PersonSummary, optionalText } from './fields.js';

export const ConnectionStatusSchema = z.enum(CONNECTION_STATUSES).meta({ id: 'ConnectionStatus' });
export const ConnectionActionSchema = z.enum(CONNECTION_ACTIONS).meta({ id: 'ConnectionAction' });

export const CreateConnectionRequest = z
  .strictObject({
    startupId: Uuid,
    message: optionalText(1000),
  })
  .meta({ id: 'CreateConnectionRequest' });
export type CreateConnectionRequest = z.input<typeof CreateConnectionRequest>;

export const ConnectionActionRequest = z
  .strictObject({ action: ConnectionActionSchema })
  .meta({ id: 'ConnectionActionRequest' });

export const StartupRef = z
  .object({ id: Uuid, slug: z.string(), name: z.string() })
  .meta({ id: 'StartupRef' });
export type StartupRef = z.infer<typeof StartupRef>;

export const ConnectionView = z
  .object({
    id: Uuid,
    status: ConnectionStatusSchema,
    startup: StartupRef,
    supporter: PersonSummary.extend({ bio: z.string().nullable() }),
    founder: PersonSummary,
    initiatorId: Uuid,
    message: z.string().nullable(),
    createdAt: IsoDateTime,
    respondedAt: IsoDateTime.nullable(),
    conversationId: Uuid.nullable(),
    /** The viewer's side of the request. */
    viewerRole: z.enum(['requester', 'recipient']),
    availableActions: z.array(ConnectionActionSchema),
    /** Either party has blocked the other. */
    blocked: z.boolean(),
  })
  .meta({ id: 'Connection' });
export type ConnectionView = z.infer<typeof ConnectionView>;

export const ConnectionListQuery = z.strictObject({
  direction: z.enum(['incoming', 'outgoing', 'all']).default('all'),
  status: ConnectionStatusSchema.optional(),
  cursor: Cursor.optional(),
  limit: z.coerce.number().int().min(1).max(50).default(20),
});

export const ConnectionPage = cursorPage(ConnectionView).meta({ id: 'ConnectionPage' });
export type ConnectionPage = z.infer<typeof ConnectionPage>;

// ── Conversations ───────────────────────────────────────────────────────────

export const MAX_MESSAGE_LENGTH = 4000;

export const MessageView = z
  .object({
    id: Uuid,
    conversationId: Uuid,
    senderId: Uuid,
    clientMessageId: Uuid,
    body: z.string(),
    createdAt: IsoDateTime,
  })
  .meta({ id: 'Message' });
export type MessageView = z.infer<typeof MessageView>;

export const ConversationSummary = z
  .object({
    id: Uuid,
    connectionId: Uuid,
    startup: StartupRef,
    counterpart: PersonSummary,
    lastMessage: z
      .object({ senderId: Uuid, preview: z.string(), createdAt: IsoDateTime })
      .nullable(),
    lastMessageAt: IsoDateTime.nullable(),
    unreadCount: z.int().min(0),
    /** Messaging is disabled (a party blocked the other or an account is suspended). */
    readOnly: z.boolean(),
  })
  .meta({ id: 'ConversationSummary' });
export type ConversationSummary = z.infer<typeof ConversationSummary>;

export const ConversationList = z
  .object({ data: z.array(ConversationSummary) })
  .meta({ id: 'ConversationList' });

export const SendMessageRequest = z
  .strictObject({
    /** Generated by the client per message; retries with the same id never duplicate. */
    clientMessageId: Uuid,
    body: z.string().trim().min(1).max(MAX_MESSAGE_LENGTH),
  })
  .meta({ id: 'SendMessageRequest' });
export type SendMessageRequest = z.input<typeof SendMessageRequest>;

export const MessageListQuery = z.strictObject({
  /** Older page: messages strictly before this cursor. */
  cursor: Cursor.optional(),
  limit: z.coerce.number().int().min(1).max(100).default(30),
});

/** Newest first; `nextCursor` loads older messages. */
export const MessagePage = cursorPage(MessageView).meta({ id: 'MessagePage' });
export type MessagePage = z.infer<typeof MessagePage>;

export const UnreadCounts = z
  .object({ messages: z.int().min(0), notifications: z.int().min(0) })
  .meta({ id: 'UnreadCounts' });
export type UnreadCounts = z.infer<typeof UnreadCounts>;
