// @ts-check
import importPlugin from 'eslint-plugin-import';
import tseslint from 'typescript-eslint';

import {
  hardCodedTextFiles,
  hardCodedTextIgnores,
  hardCodedTextSelectors,
} from './apps/web/eslint.i18n.mjs';
import { rawColourFiles, rawColourIgnores, rawColourSelectors } from './apps/web/eslint.tokens.mjs';

const bannedPrismaRawUnsafe =
  'Unsafe raw SQL is banned. Use Prisma query builders or the tagged-template $queryRaw / $executeRaw (parameterised).';

const prismaRawUnsafeSelectors = ['$queryRawUnsafe', '$executeRawUnsafe'].flatMap((name) => [
  { selector: `MemberExpression[property.name='${name}']`, message: bannedPrismaRawUnsafe },
  { selector: `MemberExpression[property.value='${name}']`, message: bannedPrismaRawUnsafe },
]);

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/out/**',
      '**/coverage/**',
      '**/playwright-report/**',
      '**/test-results/**',
      '**/storage/**',
      '**/uploads/**',
      '**/next-env.d.ts',
      'scripts/fixtures/**',
      // Prisma Client generated by `prisma generate` (gitignored).
      'apps/api/generated/**',
      // Lint fixtures are linted on purpose by their tests, never by `pnpm lint`.
      'apps/api/test/fixtures/**',
    ],
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
  },
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      import: importPlugin,
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      'import/first': 'error',
      'import/newline-after-import': 'error',
      'import/no-duplicates': 'error',
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'type'],
          pathGroups: [{ pattern: '@investfund/**', group: 'internal' }],
          pathGroupsExcludedImportTypes: ['builtin'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'no-restricted-syntax': ['error', ...prismaRawUnsafeSelectors],
    },
  },
  {
    // apps/web: visible UI copy must come from next-intl messages (see apps/web/eslint.i18n.mjs).
    files: hardCodedTextFiles,
    ignores: hardCodedTextIgnores,
    rules: {
      'no-restricted-syntax': ['error', ...prismaRawUnsafeSelectors, ...hardCodedTextSelectors],
    },
  },
  {
    // apps/web components and pages: semantic design tokens only, no raw hex or Tailwind palette
    // colours (see apps/web/eslint.tokens.mjs). Repeats the selectors above because flat config
    // replaces rule options; the i18n selectors only ever match JSX, so .ts files are unaffected.
    files: rawColourFiles,
    ignores: rawColourIgnores,
    rules: {
      'no-restricted-syntax': [
        'error',
        ...prismaRawUnsafeSelectors,
        ...hardCodedTextSelectors,
        ...rawColourSelectors,
      ],
    },
  },
  {
    // Plain JavaScript files (config files, scripts) are not part of a TS project.
    files: ['**/*.{js,mjs,cjs}'],
    ...tseslint.configs.disableTypeChecked,
  },
);
