/** Query keys, one place, so realtime events and mutations invalidate consistently. */
export const keys = {
  me: ['me'] as const,
  unread: ['unread'] as const,
  founderProfile: ['profile', 'founder'] as const,
  supporterProfile: ['profile', 'supporter'] as const,
  myStartups: ['startups', 'mine'] as const,
  myStartup: (id: string) => ['startups', 'mine', id] as const,
  search: (params: Record<string, unknown>) => ['startups', 'search', params] as const,
  relationship: (id: string) => ['startups', 'relationship', id] as const,
  saved: ['startups', 'saved'] as const,
  recommendations: ['recommendations'] as const,
  connections: (params: Record<string, unknown> = {}) => ['connections', params] as const,
  connectionsAll: ['connections'] as const,
  conversations: ['conversations'] as const,
  conversation: (id: string) => ['conversations', id] as const,
  messages: (id: string) => ['messages', id] as const,
  deals: (params: Record<string, unknown> = {}) => ['deals', params] as const,
  dealsAll: ['deals'] as const,
  deal: (id: string) => ['deal', id] as const,
  notifications: ['notifications'] as const,
  documents: (startupId: string) => ['documents', startupId] as const,
  blocks: ['blocks'] as const,
  adminOverview: ['admin', 'overview'] as const,
  adminReports: (status: string) => ['admin', 'reports', status] as const,
  adminReport: (id: string) => ['admin', 'report', id] as const,
};
