// Next.js ambient types (CSS side-effect imports, `server-only`, image imports) for a plain
// `tsc --noEmit` run. `next-env.d.ts` is generated by Next.js and is not committed.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
