import { setupWorker } from 'msw/browser';

import { handlers } from './handlers';

/** Path of the worker script generated by `pnpm --filter @investfund/web msw:init`. */
export const MOCK_SERVICE_WORKER_URL = '/mockServiceWorker.js';

let started: Promise<unknown> | undefined;

/**
 * Starts the MSW browser worker once (React Strict Mode runs effects twice). Requests without a
 * handler go to the real network. Only loaded by `ApiMocking` in `next dev` with
 * `NEXT_PUBLIC_API_MOCKING=enabled`.
 */
export function startApiMocking(): Promise<unknown> {
  started ??= setupWorker(...handlers).start({
    onUnhandledRequest: 'bypass',
    serviceWorker: { url: MOCK_SERVICE_WORKER_URL },
  });
  return started;
}
