/**
 * File storage behind an interface (Adapter pattern): local disk now, S3-compatible later.
 *
 * Keys are generated by the provider and are opaque (never the user's filename). Callers store
 * the key (`stored_files.storage_key`) and the metadata (name, type, size, hash) in the database.
 */
import type { Readable } from 'node:stream';

export interface PutOptions {
  /** Largest accepted size in bytes; capped at the provider's limit (`MAX_UPLOAD_MB`). */
  readonly maxBytes?: number;
}

export interface StoredObject {
  /** Opaque key, for example `3f/0192f0c4-7d3a-7b2c-9f1e-3a4b5c6d7e3f`. */
  readonly key: string;
  readonly sizeBytes: number;
}

export interface StorageProvider {
  /**
   * Streams `body` into storage. Rejects with `PayloadTooLargeError` as soon as the stream passes
   * the size limit, leaving nothing stored.
   */
  put(body: Readable, options?: PutOptions): Promise<StoredObject>;
  /** Rejects with `StorageObjectNotFoundError` when the key does not exist. */
  get(key: string): Promise<Readable>;
  /** Idempotent: deleting a missing key succeeds. */
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}
